import { createDeepseekClient } from '../ai/client.js';
import { parseJsonObject } from '../ai/edit-operations.js';
import type { GateResult, ReviewResult } from '../../domain/orchestration.js';

interface ReviewTaskParams {
  runPrompt: string;
  taskTitle: string;
  diff: string;
  gateResults: GateResult[];
}

function getGateByName(gateResults: GateResult[], name: string): GateResult | undefined {
  return gateResults.find((gate) => gate.name === name);
}

function shouldApproveFromGates(gateResults: GateResult[]): boolean {
  const scopeGate = getGateByName(gateResults, 'scope');
  if (scopeGate?.status === 'failed') {
    return false;
  }

  const baselineDeltaGate = getGateByName(gateResults, 'baseline-delta');
  if (baselineDeltaGate?.status === 'failed') {
    return false;
  }

  return true;
}

function parseReviewResponse(content: string): ReviewResult {
  return parseJsonObject<ReviewResult>(content);
}

function buildReviewPrompt({ runPrompt, taskTitle, diff, gateResults }: ReviewTaskParams): string {
  return `You are the reviewer agent of Unity.
Review this autonomous task result.

RUN GOAL
${runPrompt}

TASK
${taskTitle}

GATES
${gateResults.map((gate) => `- ${gate.name}: ${gate.status} -> ${gate.details}`).join('\n')}

REVIEW RULES
- Treat the "scope" gate as a hard boundary. If it fails, reject the task.
- Treat the "baseline-delta" gate as the authoritative signal for newly introduced static gate regressions.
- Do not reject a task only because a normal gate is failing if that same gate was already failing in baseline and "baseline-delta" passed.

DIFF
\`\`\`diff
${diff.substring(0, 12000)}
\`\`\`

Return JSON only:
{
  "approved": true,
  "summary": "short review summary",
  "findings": [
    { "severity": "low|medium|high", "message": "finding", "file": "optional/file.ts" }
  ],
  "followUpTasks": [
    {
      "title": "optional improvement task",
      "prompt": "executor prompt",
      "role": "executor",
      "kind": "improve",
      "writeScope": ["path"],
      "dependencies": [],
      "rationale": "why"
    }
  ]
}`;
}

export async function reviewTaskResult(params: ReviewTaskParams): Promise<ReviewResult> {
  if (!params.diff.trim()) {
    return {
      approved: true,
      summary: 'No diff generated by task.',
      findings: [],
      followUpTasks: [],
    };
  }

  const client = createDeepseekClient();

  try {
    const response = await client.chat.completions.create({
      model: 'deepseek-reasoner',
      temperature: 0.2,
      max_tokens: 1800,
      messages: [{ role: 'user', content: buildReviewPrompt(params) }],
    });

    const review = parseReviewResponse(response.choices[0]?.message?.content || '');

    return {
      approved: Boolean(review.approved),
      summary: review.summary || 'Review completed.',
      findings: Array.isArray(review.findings) ? review.findings : [],
      followUpTasks: Array.isArray(review.followUpTasks) ? review.followUpTasks : [],
    };
  } catch (error) {
    console.error('Reviewer failed, falling back to gate-based approval:', error);
    return {
      approved: shouldApproveFromGates(params.gateResults),
      summary: 'Fallback reviewer approval based on authoritative deterministic gates.',
      findings: [],
      followUpTasks: [],
    };
  }
}
